<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE correo_electronico [
    <!ELEMENT correo_electronico (mensaje)>
    <!ELEMENT mensaje (de, para, asunto, contenido)>
    <!ELEMENT de (#PCDATA)>
    <!ELEMENT para (#PCDATA)>
    <!ELEMENT asunto (#PCDATA)>
    <!ELEMENT contenido (#PCDATA)>
]>

<correo_electronico>
    <mensaje>
        <de>pepito</de>
        <para>pepita</para>
        <asunto>tenemos que hablar</asunto>
        <contenido>Me he encontrado al ni√±o en la papelera. -.-</contenido>
    </mensaje>
</correo_electronico>